version: '3'
services:
   imaginary:
        image: h2non/imaginary:latest
        volumes:
            - ./uploads:/mnt/data
        command: -enable-url-source -mount /mnt/data
        environment:
            PORT: 9000
        networks:
            - overlay
    imaginary-adapter:
        image: vlzhvlzh/imaginary-adapter
        environment:
            ADAPTER_IMAGINARY_HOST: http://imaginary:9000
            ADAPTER_FILE_PATH_PREFIX: /uploads
            ADAPTER_PORT: 9000
        ports:
            - '9000:9000'
        networks:
            - overlay
